const translations = {
  en: {brandTag:"SOLAR ENERGY",navHome:"Home",navAbout:"About",navServices:"Services",navProjects:"Process",navContact:"Contact",heroEyebrow:"POWERING A BRIGHTER FUTURE",heroTitle:"Energy from the sun.<br><em>Freedom for tomorrow.</em>",heroCopy:"Smart, reliable solar systems designed for your home and business—built to lower costs and keep your world powered.",getQuote:"Get a free consultation",explore:"Explore our solutions",statPower:"Reliable power",statYears:"Years system life",statSave:"Potential savings",aboutLabel:"ABOUT TAAQA",aboutTitle:"Clean energy.<br>Built around <em>you.</em>",aboutCopy:"Taaqa makes solar energy simple. From the first site visit to installation and long-term support, our team delivers systems that match your energy needs, budget, and ambitions.",promiseTitle:"Our promise",promiseCopy:"Clear advice, quality equipment, careful installation, and support you can count on.",servicesLabel:"WHAT WE DO",servicesTitle:"Solar solutions for<br><em>every need.</em>",servicesCopy:"End-to-end energy solutions made for the way you live and work.",s1Title:"Home Solar",s1Copy:"Lower your monthly bills and protect your home from power cuts with a tailored rooftop system.",s2Title:"Business Solar",s2Copy:"Turn unused roof space into long-term savings and dependable power for your operation.",s3Title:"Battery Storage",s3Copy:"Store clean energy during the day and use it whenever you need it—even after sunset.",s4Title:"Care & Support",s4Copy:"Keep your system performing at its best with monitoring, maintenance, and expert support.",processLabel:"HOW IT WORKS",processTitle:"From sunlight to savings in <em>four steps.</em>",processCopy:"We manage every detail so your move to solar feels simple and confident.",p1Title:"Free consultation",p1Copy:"We listen, assess your needs, and answer your questions.",p2Title:"Custom design",p2Copy:"Our engineers create the right system for your property.",p3Title:"Professional installation",p3Copy:"Our team installs, tests, and explains your new system.",p4Title:"Power & support",p4Copy:"Start saving while we continue to monitor and support you.",contactLabel:"LET'S TALK ENERGY",contactTitle:"Ready to power your<br><em>future?</em>",contactCopy:"Tell us about your home or business. We'll help you find the right solar solution.",callUs:"CALL US",emailUs:"EMAIL US",whatsapp:"Chat with us on WhatsApp",footerCopy:"Clean power. Clear future.",rights:"All rights reserved."},
  ku: {brandTag:"وزەی خۆر",navHome:"سەرەکی",navAbout:"دەربارە",navServices:"خزمەتگوزارییەکان",navProjects:"چۆنیەتی کار",navContact:"پەیوەندی",heroEyebrow:"داهاتوویەکی گەشتر بە وزە دەخەینە کار",heroTitle:"وزە لە خۆرەوە.<br><em>ئازادی بۆ سبەی.</em>",heroCopy:"سیستەمی خۆری زیرەک و متمانەپێکراو بۆ ماڵ و بازرگانی—بۆ کەمکردنەوەی خەرجی و بەردەوامی کارەبات.",getQuote:"ڕاوێژکاری بەخۆڕایی",explore:"چارەسەرەکانمان ببینە",statPower:"کارەبای متمانەپێکراو",statYears:"ساڵ تەمەنی سیستەم",statSave:"پاشەکەوتی ئەگەری",aboutLabel:"دەربارەی تاقە",aboutTitle:"وزەی پاک.<br>دروستکراوە بۆ <em>تۆ.</em>",aboutCopy:"تاقە وزەی خۆری ئاسان دەکات. لە یەکەم سەردانی شوێنەوە تا دامەزراندن و پشتگیری درێژخایەن، سیستەمێکت بۆ دابین دەکەین کە لەگەڵ پێداویستی و بودجەکەت بگونجێت.",promiseTitle:"بەڵێنی ئێمە",promiseCopy:"ڕاوێژی ڕوون، کەرەستەی کوالیتی بەرز، دامەزراندنی ورد و پشتگیری متمانەپێکراو.",servicesLabel:"چی دەکەین",servicesTitle:"چارەسەری خۆری بۆ<br><em>هەموو پێویستییەک.</em>",servicesCopy:"چارەسەری تەواوی وزە بۆ شێوازی ژیان و کارکردنت.",s1Title:"خۆر بۆ ماڵ",s1Copy:"پسوڵەی مانگانە کەم بکەرەوە و ماڵەکەت لە بڕانی کارەبا بپارێزە.",s2Title:"خۆر بۆ بازرگانی",s2Copy:"سەربانە بەتاڵەکەت بکە بە پاشەکەوت و کارەبای جێگیر بۆ کارەکەت.",s3Title:"هەڵگرتنی باتری",s3Copy:"وزەی پاک لە ڕۆژدا هەڵبگرە و هەر کات پێویستت بوو بەکاری بهێنە.",s4Title:"چاودێری و پشتگیری",s4Copy:"بە چاودێری، چاکسازی و پشتگیری پسپۆڕانە سیستەمەکەت لە باشترین ئاستدا بهێڵەرەوە.",processLabel:"چۆن کار دەکات",processTitle:"لە تیشکی خۆرەوە بۆ پاشەکەوت لە <em>چوار هەنگاو.</em>",processCopy:"ئێمە هەموو وردەکارییەکان بەڕێوە دەبەین تا گواستنەوەت بۆ وزەی خۆری ئاسان بێت.",p1Title:"ڕاوێژکاری بەخۆڕایی",p1Copy:"گوێ دەگرین، پێویستییەکانت دەزانین و وەڵامی پرسیارەکانت دەدەینەوە.",p2Title:"دیزاینی تایبەت",p2Copy:"ئەندازیارەکانمان سیستەمی گونجاو بۆ شوێنەکەت دادەڕێژن.",p3Title:"دامەزراندنی پیشەیی",p3Copy:"تیمەکەمان سیستەمەکە دادەمەزرێنێت، تاقی دەکاتەوە و ڕوونی دەکاتەوە.",p4Title:"کارەبا و پشتگیری",p4Copy:"دەست بە پاشەکەوت بکە، ئێمەش بەردەوام چاودێری و پشتگیریت دەکەین.",contactLabel:"با باسی وزە بکەین",contactTitle:"ئامادەیت وزە بە<br><em>داهاتووت بدەیت؟</em>",contactCopy:"باسی ماڵ یان بازرگانییەکەت بۆ بکە. یارمەتیت دەدەین باشترین چارەسەر بدۆزیتەوە.",callUs:"پەیوەندیمان پێوە بکە",emailUs:"ئیمەیڵمان بۆ بنێرە",whatsapp:"لە واتسئاپ قسەمان لەگەڵ بکە",footerCopy:"وزەی پاک. داهاتووی ڕوون.",rights:"هەموو مافەکان پارێزراون."},
  ar: {brandTag:"الطاقة الشمسية",navHome:"الرئيسية",navAbout:"من نحن",navServices:"خدماتنا",navProjects:"آلية العمل",navContact:"اتصل بنا",heroEyebrow:"نمنح الطاقة لمستقبل أكثر إشراقاً",heroTitle:"طاقة من الشمس.<br><em>حرية للمستقبل.</em>",heroCopy:"أنظمة شمسية ذكية وموثوقة لمنزلك وأعمالك—مصممة لخفض التكاليف والحفاظ على استمرارية الطاقة.",getQuote:"استشارة مجانية",explore:"استكشف حلولنا",statPower:"طاقة موثوقة",statYears:"عاماً من عمر النظام",statSave:"توفير محتمل",aboutLabel:"عن طاقة",aboutTitle:"طاقة نظيفة.<br>مصممة <em>لك.</em>",aboutCopy:"تجعل طاقة الانتقال إلى الطاقة الشمسية بسيطاً. من زيارة الموقع الأولى إلى التركيب والدعم طويل الأمد، نقدم نظاماً يناسب احتياجاتك وميزانيتك وطموحاتك.",promiseTitle:"وعدنا لك",promiseCopy:"نصيحة واضحة، معدات عالية الجودة، تركيب دقيق ودعم يمكنك الاعتماد عليه.",servicesLabel:"ماذا نقدم",servicesTitle:"حلول شمسية<br><em>لكل احتياج.</em>",servicesCopy:"حلول طاقة متكاملة مصممة لطريقة حياتك وعملك.",s1Title:"الطاقة الشمسية للمنازل",s1Copy:"خفّض فواتيرك الشهرية واحمِ منزلك من انقطاع الكهرباء بنظام مصمم خصيصاً لك.",s2Title:"الطاقة الشمسية للأعمال",s2Copy:"حوّل مساحة السطح غير المستخدمة إلى توفير طويل الأمد وطاقة مستقرة لأعمالك.",s3Title:"تخزين البطاريات",s3Copy:"خزّن الطاقة النظيفة نهاراً واستخدمها وقتما تحتاج إليها—حتى بعد الغروب.",s4Title:"العناية والدعم",s4Copy:"حافظ على أفضل أداء لنظامك من خلال المراقبة والصيانة ودعم الخبراء.",processLabel:"كيف نعمل",processTitle:"من أشعة الشمس إلى التوفير في <em>أربع خطوات.</em>",processCopy:"ندير كل التفاصيل لتكون رحلتك نحو الطاقة الشمسية سهلة وواثقة.",p1Title:"استشارة مجانية",p1Copy:"نستمع إليك، ونقيّم احتياجاتك ونجيب عن أسئلتك.",p2Title:"تصميم مخصص",p2Copy:"يصمم مهندسونا النظام المناسب لموقعك.",p3Title:"تركيب احترافي",p3Copy:"يقوم فريقنا بالتركيب والاختبار وشرح نظامك الجديد.",p4Title:"الطاقة والدعم",p4Copy:"ابدأ بالتوفير بينما نستمر في المراقبة ودعمك.",contactLabel:"لنتحدث عن الطاقة",contactTitle:"هل أنت مستعد لتمنح<br><em>مستقبلك الطاقة؟</em>",contactCopy:"أخبرنا عن منزلك أو عملك، وسنساعدك في إيجاد الحل الشمسي المناسب.",callUs:"اتصل بنا",emailUs:"راسلنا",whatsapp:"تحدث معنا عبر واتساب",footerCopy:"طاقة نظيفة. مستقبل واضح.",rights:"جميع الحقوق محفوظة."}
};
Object.assign(translations.en,{navProjects:"Projects",videoLabel:"TAAQA IN ACTION",videoTitle:"See the energy.<br><em>See the difference.</em>",videoCopy:"Take a closer look at our work and the solar solutions we deliver."});
Object.assign(translations.ku,{navProjects:"پڕۆژەکان",videoLabel:"تاقە لە کاردا",videoTitle:"وزەکە ببینە.<br><em>جیاوازییەکە ببینە.</em>",videoCopy:"لە نزیکەوە سەیری کار و چارەسەرە خۆرییەکانمان بکە."});
Object.assign(translations.ar,{navProjects:"المشاريع",videoLabel:"طاقة على أرض الواقع",videoTitle:"شاهد الطاقة.<br><em>شاهد الفرق.</em>",videoCopy:"ألقِ نظرة أقرب على أعمالنا وحلول الطاقة الشمسية التي نقدمها."});

function setLanguage(lang){
  const dictionary=translations[lang]||translations.en;
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==='en'?'ltr':'rtl';
  document.querySelectorAll('[data-i18n]').forEach(el=>{const value=dictionary[el.dataset.i18n];if(value)el.innerHTML=value});
  document.querySelectorAll('[data-lang]').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));
  localStorage.setItem('taaqa-language',lang);
}
document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
const menu=document.querySelector('.nav'),toggle=document.querySelector('.menu-toggle');
toggle.addEventListener('click',()=>{menu.classList.toggle('open');toggle.setAttribute('aria-expanded',menu.classList.contains('open'))});
document.querySelectorAll('.nav a').forEach(link=>link.addEventListener('click',()=>menu.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
setLanguage(localStorage.getItem('taaqa-language')||'en');

if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){
  const tilt=(element,xName,yName,strength=8)=>{
    element.addEventListener('pointermove',event=>{const box=element.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;element.style.setProperty(xName,`${-y*strength}deg`);element.style.setProperty(yName,`${x*strength}deg`)});
    element.addEventListener('pointerleave',()=>{element.style.setProperty(xName,'0deg');element.style.setProperty(yName,'0deg')});
  };
  document.querySelectorAll('.service-card').forEach(card=>tilt(card,'--rx','--ry',9));
  document.querySelectorAll('.video-stage').forEach(stage=>tilt(stage,'--vx','--vy',4));
  const contact=document.querySelector('.contact-content');if(contact)tilt(contact,'--contact-rx','--contact-ry',3);
  const hero=document.querySelector('.hero'),heroContent=document.querySelector('.hero-content');
  if(hero&&heroContent)hero.addEventListener('pointermove',event=>{const x=event.clientX/innerWidth-.5,y=event.clientY/innerHeight-.5;hero.style.setProperty('--hero-x',`${x*18}px`);hero.style.setProperty('--hero-y',`${y*12}px`);heroContent.style.setProperty('--content-x',`${x*-9}px`);heroContent.style.setProperty('--content-y',`${y*-7}px`)});
  let ticking=false;addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{document.querySelector('.site-header')?.classList.toggle('scrolled',scrollY>30);ticking=false});ticking=true}},{passive:true});
}
